version: "3.4"
services:
  client:
    container_name: client
    restart: always
    build:
      context: ./client
      args:
        REACT_APP_SERVER_HOST: "server"
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    networks:
      - app-network
    environment:
      - PORT=3000
      - REACT_APP_SERVER_HOST=${REACT_APP_SERVER_HOST}
    links:
      - server

  server:
    container_name: server
    restart: always
    build: ./server
    ports:
      - ${SERVER_PORT}:3008
    networks:
      - app-network

networks:
  app-network:
    driver: bridge