version: "3.4"
services:
  client:
    container_name: client
    restart: always
    build:
      context: ./client
      args:
        REACT_APP_SERVER_HOST: "server"
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    networks:
      - app-network
    environment:
      - PORT=3000
      - REACT_APP_SERVER_HOST=${REACT_APP_SERVER_HOST}
    links:
      - server

  server:
    container_name: server
    restart: always
    build: ./server
    ports:
      - ${SERVER_PORT}:3006
    networks:
      - app-network
#    links:
#      - database

#  database:
#    container_name: sql
#    image: mysql:8.0.21
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    ports:
#      - ${DATABSE_PORT}:3306
#    environment:
#      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#      - MYSQL_USER=${DB_USER}
#      - MYSQL_PASSWORD=${DB_PASSWORD}
#      - MYSQL_DATABASE=${DB_NAME}
#    networks:
#      - app-network

networks:
  app-network:
    driver: bridge